name: OCR Poetry Benchmark Tests
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ocr-benchmarks.yml
      - OCR/**
jobs:
  build:
    runs-on: runner-set-1
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          cd OCR/tests
          python -m pip install --upgrade pip
          pip install poetry
          pip install pytest pytest-benchmark
          poetry install --with dev
      - name: Run tests
        run: |
          cd OCR/tests
          poetry run pytest bench_test.py -v --benchmark-json output.json
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          tool: 'pytest'
          output-file-path: OCR/tests/output.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
